# 你的头像url
avatar: /avatar.jpg
favicon: /avatar.jpg

#链接图标，链接为空则不显示
link:
  github: https://github.com/yelog
  weibo: http://weibo.com/u/2307534817
  twitter:
  linkedin:
  instagram:
  mail: jaytp@qq.com


# Table of contents | 文章目录
toc:
  max_depth: 3  # 1 - 6 (h1-h6) 目录最大级数


preload_comment: true
## false: 当点击评论条等区域时再加载评论模块

disqus:
  on: true
  shortname: yelog
  # https://help.disqus.com/customer/en/portal/articles/466208-what-s-a-shortname-
  # It is unnecessary to enable disqus here if
  # you have set "disqus_shortname" in your site's "_config.yml"

# 暂时还有些问题，建议使用disqus
duoshuo:
  on: false
  domain: jaytp
  # 是否开启多说评论，http://duoshuo.com/create-site/
  # 使用上面网址登陆你的多说，然后创建站点，在 domain 中填入你设定的域名前半部分
  # http://<要填的部分>.duoshuo.com (domain只填上<>里的内容，不要填整个网址)

youyan:
  on: false


CDN:
  jquery: //cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js
  highlight: //cdnjs.cloudflare.com/ajax/libs/highlight.js/9.9.0/highlight.min.js
  pjax: //cdnjs.cloudflare.com/ajax/libs/jquery.pjax/1.9.6/jquery.pjax.min.js
  animate: //cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css
  font_awsome: //cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css

