# 你的头像url
avatar: /img/avatar.jpg
favicon: /img/avatar.jpg

#链接图标，链接为空则不显示
link:
  rss: /atom.xml
  github: https://github.com/yelog
  facebook: https://www.facebook.com/faker.tops
  twitter:
  linkedin: https://www.linkedin.com/in/%E7%8E%89%E6%9D%B0-%E6%9D%A8-13a40a103/
  instagram:
  reddit: https://www.reddit.com/user/yelog/
  weibo: http://weibo.com/u/2307534817
  email: jaytp@qq.com

##########多作者模式############
author:
  on: false
  authors:
    author1: 阿杰
    author2: 小马哥
##############################

# 文末声明
article_txt: 转载请注明来源，欢迎对文章中的引用来源进行考证，欢迎指出任何有错误或不够清晰的表达。可以在下面评论区评论，也可以邮件至 jaytp@qq.com

bottom_text: ©2017 Yelog
# 自定义页面最下方的站点版权信息
# 如果不填，则自定义为 ©2017 author (这个author为hexo根目录_config.yml中配置的)

reward: true
# true 开启打赏功能

searchAll: false
# true 启用全文搜索
# 开启此功能需要下面操作：
# 1. 在 hexo 根目录 执行 npm install hexo-generator-search --save 安装插件
# 2. 在 hexo 根目录的 _config.xml 中添加下面内容
# search:
#   path: search.xml
#   field: post


copyright: true
# Copyright info. of post | 文末版权信息

word_count: false
# true 开启字数统计
# 开启此功能需要安装插件 ：在 hexo根目录 执行npm i hexo-wordcount --save


# 不蒜子网站计数设置
# http://ibruce.info/2015/04/04/busuanzi/
visit_counter:
  on: true
  site_visit: true
  page_visit: true

##########自定义样式设置##############
# Table of contents | 文章目录
toc:
  max_depth: 3  # 1 - 6 (h1-h6) 目录最大级数

#文章列表 鼠标移上去的样式, 为空时使用默认效果
article_list:
  hover:
    background: '#e2e0e0'  # 背景色:提供几种：'#c1bfc1'  '#fbf4a8'
    color:     # 文字颜色 提供几种：'#ffffff'
# 注意：由于颜色如果包含#，使用单引号 ' 引起来

# 列表样式
list: thread
# normal : 普通样式
# thread : 列表外圈有一个线框

# 引用块样式
blockquote: bracket
# github : 类似于github的引用快
# bracket : 类似于左右两个大括号的样式

# table 的样式
table: green_title
# 为空时类似github的table样式
# green 绿色样式
# green_title 头部为青色的table样式

# 文章列表背景图
article_bg_img:
  on: true
  src: http://oncj6b2vl.bkt.clouddn.com/FlSExUGfRSaqxkK5v42CpuI-tXAL.jpg

highlight:
  on: true # true开启代码高亮
  lineNum: true # true显示行号
  theme: atom-light
# 代码高亮主题,效果可以查看 https://highlightjs.org/static/demo/
# 支持主题：
# sublime : 参考sublime的高亮主题
# darcula : 参考idea中的darcula的主题
# atom-dark : 参考Atom的dark主题
# atom-light : 参考Atom的light主题
# github : 参考GitHub版的高亮主题
# github-gist : GitHub-Gist主题
# brown-paper : 牛皮纸效果
# gruvbox-light : gruvbox的light主题
# gruvbox-dark ： gruvbox的dark主题
# rainbow :
# railscasts :
# sunburst :
# kimbie-dark :
# kimbie-light :
# school-book : 纸张效果
# zenbum : oschina 也选择此高亮主题

# MathJax 数学公式支持
mathjax:
  on: true #是否启用
  per_page: false # 若只渲染单个页面，此选项设为false，页面内加入 mathjax: true

##############################

# 友情链接
friends:
  叶落阁: http://yelog.org/

##########评论设置#############
comment_count: true
# 文章标题下方显示评论数

preload_comment: false
# 预加载评论区
## false: 当点击评论条等区域时再加载评论模块
## true: 页面加载时加载评论区

disqus:
  on: false
  shortname: yelog
  # disqus评论系统， 2016年9月被GFW认证，大陆不能使用。
  # https://help.disqus.com/customer/en/portal/articles/466208-what-s-a-shortname-

gentie:
  on: false
  product_key: 
  # 网易云跟帖评论系统，https://gentie.163.com/
  # 注册后，进入后台管理，获取代码：复制其中的productKey到product_key中。
  # 网易云跟帖暂时不支持查询评论数，所以启用时，把评论数关掉，上方comment_count: false。

gitalk:
  on: false
  githubID: yelog
  repo: yelog.github.io
  ClientID: 
  ClientSecret: 
  adminUser: yelog
  distractionFreeMode: true
  language: zh-CN
  perPage: 10
# gitalk：利用github issue制作的第三方聊天插件
# https://github.com/gitalk/gitalk
# 参数介绍：
# githubID: github用户名
# repo: 使用哪个仓库的issue
# ClientID 和 ClientSecret 创建 OAuth application 就会生成：https://github.com/settings/applications/new
# adminUser: 必须为上面仓库的合作者（有写入权限），使用自己的 github 用户名即可
# distractionFreeMode: 全屏遮罩效果
# language: 语言：支持：en / zh-CN / zh-TW 三种
# perPage: 每次加载的数据大小，默认10，最大100


gitment:
  on: false
  owner: yelog
  repo: yelog.github.io
  client_id: 
  client_secret: 
  # gitment : 通过github issue实现的评论系统
  # 开源地址 : https://github.com/imsun/gitment
  # 使用说明 :
  #

##############################

##########CND设置#############
CDN:
  jquery: //cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js
  jquery_ui: //cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js
  jquery_ui_css: //cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css
  highlight: //cdnjs.cloudflare.com/ajax/libs/highlight.js/9.9.0/highlight.min.js
  pjax: //cdnjs.cloudflare.com/ajax/libs/jquery.pjax/1.9.6/jquery.pjax.min.js
  animate: //cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css
  font_awsome: //cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css
  nprogres_js: //cdnjs.cloudflare.com/ajax/libs/nprogress/0.2.0/nprogress.min.js
  mathjax: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML
##############################
